import './js/counter';
import './js/gallery';
import './js/lightbox';
import './js/mobile-menu';
import './js/modal';
import './js/scroll';
import './js/scrolltoup';
import './js/slick.min';
import './js/slider';
